language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository


script:
    - ./gradlew clean test
